# Site settings
title: Synereo
email: founders@synereo.com
description: The Decentralized and Distributed Social Network
baseurl: ""
url: "http://synereo.com"
twitter_username: synereo
github_username:  synereo

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
